Q1. Create 20000 × 10000 data file using random module

In [2]:
import random
import csv

rows = 20000
cols = 10000

with open("large_matrix.csv", "w", newline="") as file:
    writer = csv.writer(file)

    for _ in range(rows):
        row = random.choices(range(100), k=cols)
        writer.writerow(row)



Q2. Assign subsequent rows to matrix first row elements

In [3]:
import numpy as np

# Example matrix
matrix = np.array([
    [10, 20, 30],
    [1, 2, 3],
    [4, 5, 6]
])

first_row = matrix[0]
remaining_rows = matrix[1:]

result = {}

for i in range(len(first_row)):
    result[first_row[i]] = remaining_rows[:, i]

print(result)


{np.int64(10): array([1, 4]), np.int64(20): array([2, 5]), np.int64(30): array([3, 6])}


Q3. Group similar elements into matrix

In [4]:
import numpy as np
from collections import defaultdict

matrix = np.array([
    [1, 2, 2],
    [3, 1, 3],
    [2, 3, 1]
])

groups = defaultdict(list)

for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        groups[matrix[i][j]].append((i, j))

print("Grouped Elements:")
for key, value in groups.items():
    print(key, ":", value)


Grouped Elements:
1 : [(0, 0), (1, 1), (2, 2)]
2 : [(0, 1), (0, 2), (2, 0)]
3 : [(1, 0), (1, 2), (2, 1)]


Q4. Add and Subtract Matrices

In [5]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

addition = A + B
subtraction = A - B

print("Addition:\n", addition)
print("Subtraction:\n", subtraction)


Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]


Q5. Create n × n matrix where opposite corners sum is even

In [6]:
import numpy as np

n = int(input("Enter n: "))

matrix = np.zeros((n, n), dtype=int)

for i in range(n):
    for j in range(n):
        matrix[i][j] = 2 * (i + j)  # ensures even numbers

print("Matrix:\n", matrix)


Enter n: 4
Matrix:
 [[ 0  2  4  6]
 [ 2  4  6  8]
 [ 4  6  8 10]
 [ 6  8 10 12]]


Q6. Row-wise element addition in tuple matrix

In [7]:
matrix = (
    (1, 2, 3),
    (4, 5, 6),
    (7, 8, 9)
)

row_sums = []

for row in matrix:
    row_sums.append(sum(row))

print("Row-wise sums:", row_sums)


Row-wise sums: [6, 15, 24]
